### PR TITLE
Support for terminating commands in SPI BFM and VVC for slave side

### PR DESCRIPTION
**Pull request by am9417**
- Added `terminate_loop` input signal in bitvis_vip_spi's BFM slave side procedures
- Wait clauses wait for `terminate_loop` signal to activate, too
- Connected the `terminate_current_cmd` flag in the VVC to slave BFM commands

### CODE REVIEW

**Comment by mariuselv** [comment]
Hi,
We need to ensure that this PR is backwards compatible, i.e. there has to be overloads with the terminate_access signal in addition to the original BFM procedure signature.

Br,
Marius

**Comment by UVVM** [comment]
Create overloading procedures, without the terminate_access formal, which calls the new procedure with terminate_access set to '0'. Will have to be done for all changed procedures.

E.g.

```
procedure spi_slave_receive(
    variable rx_data                : out std_logic_vector;
    constant msg                    : in string;
    signal   spi_if                 : inout t_spi_if;
    signal   terminate_access       : in std_logic;
    constant when_to_start_transfer : in t_when_to_start_transfer := START_TRANSFER_ON_NEXT_SS;
    constant scope                  : in string                   := C_SCOPE;
    constant msg_id_panel           : in t_msg_id_panel           := shared_msg_id_panel;
    constant config                 : in t_spi_bfm_config         := C_SPI_BFM_CONFIG_DEFAULT
  ) is begin

.... code for spi_slave_receive

end procedure spi_slave_receive;

-- overloading procedure
procedure spi_slave_receive(
  variable rx_data                : out std_logic_vector;
  constant msg                    : in string;
  signal   spi_if                 : inout t_spi_if;
  constant when_to_start_transfer : in t_when_to_start_transfer := START_TRANSFER_ON_NEXT_SS;
  constant scope                  : in string                   := C_SCOPE;
  constant msg_id_panel           : in t_msg_id_panel           := shared_msg_id_panel;
  constant config                 : in t_spi_bfm_config         := C_SPI_BFM_CONFIG_DEFAULT
) is begin

  -- calling overloaded procedure
  procedure spi_slave_receive(
    rx_data <= rx_data,
    msg <= msg,
    spi_if <= spi_if,
    terminate_access <= '0',
    when_to_start_transfer <= when_to_start_transfer,
    scope <= scope,
    msg_id_panel <= msg_id_panel,
    config <= config
  );

end  procedure spi_slave_receive;
```

**Comment by am9417** [comment]
Ok, that's what I was "afraid" of.
I'll do the changes.

**Comment by am9417** [comment]
I've modified the bfm package with the overloads that don't have terminate_access parameter

**Pull request merged**
